name: Doc checks

on:
  # Runs when manually triggered from the GitHub UI.
  workflow_dispatch:

  # Runs when invoked by another workflow.
  workflow_call:

jobs:
  doc_checks:
    name: Doc checks
    uses: apify/workflows/.github/workflows/python_docs_check.yaml@main

  # tmp
  doc_tests:
    name: Doc release test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Enable Corepack
        run: corepack enable

      # Install Node dependencies and update docs theme to the latest version
      - name: Install Node dependencies
        run: |
          yarn install
          yarn up @apify/docs-theme
        working-directory: ./website
