name: Doc release

on:
  # Runs when manually triggered from the GitHub UI.
  workflow_dispatch:

  # Dry-run trigger for docs migration branch.
  push:
    branches:
      - migrate-docs-to-yarn

  # Runs when invoked by another workflow.
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  NODE_VERSION: 22
  PYTHON_VERSION: 3.14
  CHECKOUT_REF: ${{ github.event_name == 'workflow_call' && inputs.ref || github.ref }}

jobs:
  release_docs:
    name: Doc release
    environment:
      name: github-pages
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}
          ref: ${{ env.CHECKOUT_REF }}

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node dependencies
        run: |
          yarn install
          yarn up @apify/docs-theme
        working-directory: ./website

      # We do this as early as possible to prevent conflicts if someone else would push something in the meantime
      - name: Commit the updated package.json and lockfile
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add website/package.json
          git add website/yarn.lock
          git diff-index --quiet HEAD || git commit -m 'chore: Automatic docs theme update [skip ci]' || true
          git push

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: uv run poe install-dev

      - name: Build docs
        run: uv run poe build-docs
        env:
          APIFY_SIGNING_TOKEN: ${{ secrets.APIFY_SIGNING_TOKEN }}
